"use client";

import { Amplify } from "aws-amplify";

// amplify_outputs.json is generated by Amplify CI/CD.
// The landing page works without it — the require warning is expected
// during local development without a deployed backend.
try {
  // eslint-disable-next-line @typescript-eslint/no-require-imports
  const outputs = require("@/amplify_outputs.json");
  Amplify.configure(outputs, { ssr: true });
} catch {
  // no-op
}

export default function Providers({ children }: { children: React.ReactNode }) {
  return <>{children}</>;
}
